# Generated by Django 4.2.1 on 2023-05-25 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mgt_app", "0003_order_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="Product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mgt_app.product",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mgt_app.customer",
            ),
        ),
    ]
