# Generated by Django 4.2.1 on 2023-05-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mgt_app", "0004_order_product_order_customer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="tag",
            field=models.ManyToManyField(to="mgt_app.tag"),
        ),
    ]
