# Generated by Django 4.2.1 on 2023-05-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mgt_app", "0005_tag_order_tag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="tag",
        ),
        migrations.AddField(
            model_name="product",
            name="tag",
            field=models.ManyToManyField(to="mgt_app.tag"),
        ),
    ]
