# Generated by Django 4.2.1 on 2023-05-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mgt_app", "0006_remove_order_tag_product_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
