# Generated by Django 4.2.1 on 2023-05-25 13:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mgt_app", "0007_alter_product_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="Product",
            new_name="product",
        ),
    ]
